""" Scans
"""
ID = 'id'
DATE = 'date'
LINE = 'line'
DIR = 'dir'
GEOM = 'geom'
USER_ID = 'user_id'
STOP = 'stop'

""" Pairs - Scans
"""
#ID = 'id'
ON_ID = 'on_id'
OFF_ID = 'off_id'

""" Pairs - Stops
"""
#ID = 'id'
#DATE = 'date'
#LINE = 'line'
#DIR = 'dir'
ON_STOP = 'on_stop'
OFF_STOP = 'off_stop'
#USER_ID = 'user_id'

""" Surveys - Core
"""
URI = 'uri'
USER = 'user'
MARK_COMPLETE = 'mark_complete'
SUBMISSION_DATE = 'submission_date'
DEVICEID = 'deviceid'
START = 'start'
END = 'end'
ENGLISH = 'english'
OTHER_LNG = 'other_lng'
RTE = 'rte'
#DIR = 'dir'
ORIG_PURPOSE = 'orig_purpose'
ORIG_PURPOSE_OTHER = 'orig_purpose_other'
ORIG_LAT = 'orig_lat'
ORIG_LNG = 'orig_lng'
ORIG_GEOM = 'orig_geom'
ORIG_ACCESS = 'orig_access'
ORIG_ACCESS_OTHER = 'orig_access_other'
ORIG_BLOCKS = 'orig_blocks'
ORIG_PARKING = 'orig_parking'
DEST_PURPOSE = 'dest_purpose'
DEST_PURPOSE_OTHER = 'dest_purpose_other'
DEST_LAT = 'dest_lat'
DEST_LNG = 'dest_lng'
DEST_GEOM = 'dest_geom'
DEST_ACCESS = 'dest_access'
DEST_ACCESS_OTHER = 'dest_access_other'
DEST_BLOCKS = 'dest_blocks'
DEST_PARKING = 'dest_parking'
BOARD_ID = 'board_id'
ALIGHT_ID = 'alight_id'
BOARD_STOP = 'board_stop'
ALIGHT_STOP = 'alight_stop'
TRANSFERS_BEFORE = 'transfers_before'
TB_1 = 'tb_1'
TB_2 = 'tb_2'
TB_3 = 'tb_3'
TRANSFERS_AFTER = 'transfers_after'
TA_1 = 'ta_1'
TA_2 = 'ta_2'
TA_3 = 'ta_3'
STCAR_FARE = 'stcar_fare'
STCAR_FARE_OTHER = 'stcar_fare_other'
CHURN = 'churn'
CHURN_OTHER = 'churn_other'
REASON = 'reason'
LICENSE = 'license'
HOUSE_NO = 'house_no'
WRK_OUT_HOUSE = 'wrk_out_house'
WRK_VCHL = 'wrk_vchl'
RACE = 'race'
RACE_OTHER = 'race_other'
INCOME = 'income'
ADDIT_LNG = 'addit_lng'
OTHER_LNG_OTHER = 'other_lng_other'
ENGLISH_PROF = 'english_prof'
VALID = 'valid'

""" Survey - Lng
"""
#URI = 'uri'
PARENT_URI = 'parent_uri'
VALUE = 'value'

